### ISSUE TITLE
I get react/prop-types errors for this.props.children

### ISSUE THREAD

**Issue by tburry** [vanilla/eslint-config#1]
When I refer to this.props.children in a component I am getting: **ESLinit: 'children' is missing in props validation (react/prop-types)**. I'm not sure this needs to be so strictly enforced.

**Comment by charrondev** [comment]
eslint-plugin-react has a option to allow you to ignore specific prop validation such as children. https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md#rule-options

It used to be default but isn't anymore. Should be easy enough to add here.

**Comment by charrondev** [comment]
Additionally I should go through the list and ensure the react type validations are all ok.

**Comment by tburry** [comment]
I read a github issue with a debate on the issue and I think it's best to leave this as is. If I make a component that references children than I can put it in propTypes with:

```js
Component.propTypes = {
    children: PropTypes.node,
}
```

Since components don't reference children that much I think this is the correct thing to do.
